debuggerd: Resolve tombstoned missing O_CREAT mode
 debuggerd/tombstoned/tombstoned.cpp:115:92:
  error: 'openat' has superfluous mode bits; missing O_CREAT?
    unique_fd result(openat(dir_fd_, ".",
    O_WRONLY | O_APPEND | O_TMPFILE | O_CLOEXEC, 0640));

Change-Id: Iae787e477b7eab1f11c79f30c35fd6808959e38a

Former-commit-id: 4645d8e1fbca878ce1b52a422eb39fcaf49685e6
Former-commit-id: 8249f98e6c30be1da6e01e0a737fd26144eda745
Former-commit-id: bf12d876b33f9c57b03d629c4ea63cb32feaa6a9
Former-commit-id: 44a753ed53b7e5dd0651f2abda49ef9f45528a4a