Revert "adb: add transport benchmark."
This reverts commit 698e234835f1fc1e6511803ddc1a76ca4d505ba1.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293